#!/usr/bin/env bash
# Bash script must accept 2 arguments: domain, subdomain:
# The subdomain [SUB_DOMAIN] is a [RECORD_TYPE] record and points to [DESTINATION]

info () {
#    data=$(dig "$2"."$1" | awk '/ANSWER SECTION:/ {getline; print}' | awk '{print $1, $4}')
    echo "$(dig www.$1 | awk '/ANSWER SECTION:/{getline; print "The subdomain www is a " $4 " record and points to " $5}')"
    echo "$(dig web-01.$1 | awk '/ANSWER SECTION:/{getline; print "The subdomain web-01 is a " $4 " record and points to " $5}')"
    echo "$(dig web-02.$1 | awk '/ANSWER SECTION:/{getline; print "The subdomain web-02 is a " $4 " record and points to " $5}')"
    echo "$(dig lb-01.$1 | awk '/ANSWER SECTION:/{getline; print "The subdomain lb-01 is a " $4 " record and points to " $5}')"
}

if [ "$#" == 1 ];then
        info "$1"
fi


if [ "$#" == 2 ]
then
  info "$1" "$2"
fi
